{
  "results": {
    "violations": [
      {
        "rule_name": "docFilePlatformFlag",
        "description": "Ensure platform flag with FROM command is not used for Docker file",
        "rule_id": "AC_DOCKER_0001",
        "severity": "HIGH",
        "category": "Infrastructure Security",
        "resource_name": "Dockerfile",
        "resource_type": "docker_FROM",
        "file": "Dockerfile",
        "line": 1
      }
    ],
    "skipped_violations": null,
    "scan_summary": {
      "file/folder": "/Users/suvarna/go/src/github.com/rchanger/terrascan/test/e2e/test_data/iac/resource_prioritising/min_severity_set/docker",
      "iac_type": "docker",
      "scanned_at": "2021-08-06 10:30:28.495621 +0000 UTC",
      "policies_validated": 9,
      "violated_policies": 1,
      "low": 0,
      "medium": 0,
      "high": 1
    }
  }
}
