version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
    "docs/**",
    "scripts/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/accurics/terrascan"]
