{
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0-rtm.5.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "informationUri": "https://github.com/tenable/terrascan",
          "name": "terrascan",
          "rules": [
            {
              "id": "AC_DOCKER_0001",
              "name": "docFilePlatformFlag",
              "shortDescription": {
                "text": "Ensure platform flag with FROM command is not used for Docker file"
              },
              "properties": {
                "category": "Infrastructure Security",
                "severity": "MEDIUM"
              }
            }
          ],
          "version": "1.17.0"
        }
      },
      "results": [
        {
          "ruleId": "AC_DOCKER_0001",
          "ruleIndex": 0,
          "level": "warning",
          "message": {
            "text": "Ensure platform flag with FROM command is not used for Docker file"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///Users/suvarna/go/src/github.com/rchanger/terrascan/test/e2e/test_data/iac/docker/dockerfile_with_platform_flag_violation/Dockerfile"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "name": "Dockerfile",
                  "kind": "docker_FROM"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
