

Violation Details -
    
	Description    :	Ensure platform flag with FROM command is not used for Docker file
	File           :	Dockerfile
	Line           :	1
	Severity       :	MEDIUM
	Rule Name      :	docFilePlatformFlag
	Rule ID        :	AC_DOCKER_0001
	Resource Name  :	Dockerfile
	Resource Type  :	docker_FROM
	Category       :	Infrastructure Security
	
	-----------------------------------------------------------------------
	

Scan Summary -

	File/Folder         :	/Users/suvarna/go/src/github.com/rchanger/terrascan/test/e2e/test_data/iac/docker
	IaC Type            :	docker
	Scanned At          :	2021-08-06 12:56:35.047008 +0000 UTC
	Policies Validated  :	9
	Violated Policies   :	1
	Low                 :	0
	Medium              :	1
	High                :	0
	

