apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.cert_secret_name }}
  namespace: {{ .Release.Namespace }}
data:
{{- if and (eq "" .Values.secrets.tlsCertFilePath) (eq "" .Values.secrets.tlsKeyFilePath) }}

# alternate names of the services
{{- $altNames := list ( printf "%s.%s.svc.cluster.local" .Values.name .Release.Namespace ) }}
# generate ca cert with 365 days of validity
{{- $ca := genCA ( printf "%s-server-ca" "terrascan" ) 365 }}
# generate cert with CN="component-svc", SAN=$altNames and with 365 days of validity
{{- $certterrascan := genSignedCert ( printf "%s-server" "terrascan" ) nil $altNames 365 $ca }}
  tls.crt: {{ $certterrascan.Cert | b64enc }}
  tls.key: {{ $certterrascan.Key | b64enc }}
{{- else }}
  tls.crt: {{ .Files.Get (printf "%s" .Values.secrets.tlsCertFilePath) | b64enc }}
  tls.key: {{ .Files.Get (printf "%s" .Values.secrets.tlsKeyFilePath) | b64enc }}

{{- end }}