apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssh_secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  private-key: |-
    {{ .Files.Get ".ssh/private_key" | b64enc }}
  known-hosts: |-
    {{ .Files.Get ".ssh/known_hosts" | b64enc }}
