resources:
  - ../base
  - service.yaml

namespace: <TERRASCAN_NAMESPACE>

commonLabels:
  app: terrascan

secretGenerator:
  - name: terrascan-certs-secret
    files:
      - server.key=certs/server.key
      - server.crt=certs/server.crt

patchesStrategicMerge:
  - deployment-certs.yaml
